/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MasukRouteImport } from './routes/masuk'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRiwayatkuRouteImport } from './routes/_authenticated/riwayatku'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedPesanRouteImport } from './routes/_authenticated/pesan'
import { Route as AuthenticatedNotifikasiRouteImport } from './routes/_authenticated/notifikasi'
import { Route as AuthenticatedJelajahiRouteImport } from './routes/_authenticated/jelajahi'
import { Route as AuthenticatedBerandaRouteImport } from './routes/_authenticated/beranda'
import { Route as AuthenticatedBantuankuRouteImport } from './routes/_authenticated/bantuanku'
import { Route as AuthenticatedPesanPeerIdRouteImport } from './routes/_authenticated/pesan.$peerId'
import { Route as AuthenticatedJelajahiCategoryRouteImport } from './routes/_authenticated/jelajahi.$category'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MasukRoute = MasukRouteImport.update({
  id: '/masuk',
  path: '/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRiwayatkuRoute = AuthenticatedRiwayatkuRouteImport.update({
  id: '/riwayatku',
  path: '/riwayatku',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesanRoute = AuthenticatedPesanRouteImport.update({
  id: '/pesan',
  path: '/pesan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotifikasiRoute = AuthenticatedNotifikasiRouteImport.update({
  id: '/notifikasi',
  path: '/notifikasi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJelajahiRoute = AuthenticatedJelajahiRouteImport.update({
  id: '/jelajahi',
  path: '/jelajahi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBerandaRoute = AuthenticatedBerandaRouteImport.update({
  id: '/beranda',
  path: '/beranda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBantuankuRoute = AuthenticatedBantuankuRouteImport.update({
  id: '/bantuanku',
  path: '/bantuanku',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesanPeerIdRoute =
  AuthenticatedPesanPeerIdRouteImport.update({
    id: '/$peerId',
    path: '/$peerId',
    getParentRoute: () => AuthenticatedPesanRoute,
  } as any)
const AuthenticatedJelajahiCategoryRoute =
  AuthenticatedJelajahiCategoryRouteImport.update({
    id: '/$category',
    path: '/$category',
    getParentRoute: () => AuthenticatedJelajahiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bantuanku': typeof AuthenticatedBantuankuRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/jelajahi': typeof AuthenticatedJelajahiRouteWithChildren
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/pesan': typeof AuthenticatedPesanRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/riwayatku': typeof AuthenticatedRiwayatkuRoute
  '/jelajahi/$category': typeof AuthenticatedJelajahiCategoryRoute
  '/pesan/$peerId': typeof AuthenticatedPesanPeerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/bantuanku': typeof AuthenticatedBantuankuRoute
  '/beranda': typeof AuthenticatedBerandaRoute
  '/jelajahi': typeof AuthenticatedJelajahiRouteWithChildren
  '/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/pesan': typeof AuthenticatedPesanRouteWithChildren
  '/profil': typeof AuthenticatedProfilRoute
  '/riwayatku': typeof AuthenticatedRiwayatkuRoute
  '/jelajahi/$category': typeof AuthenticatedJelajahiCategoryRoute
  '/pesan/$peerId': typeof AuthenticatedPesanPeerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/masuk': typeof MasukRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/bantuanku': typeof AuthenticatedBantuankuRoute
  '/_authenticated/beranda': typeof AuthenticatedBerandaRoute
  '/_authenticated/jelajahi': typeof AuthenticatedJelajahiRouteWithChildren
  '/_authenticated/notifikasi': typeof AuthenticatedNotifikasiRoute
  '/_authenticated/pesan': typeof AuthenticatedPesanRouteWithChildren
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/riwayatku': typeof AuthenticatedRiwayatkuRoute
  '/_authenticated/jelajahi/$category': typeof AuthenticatedJelajahiCategoryRoute
  '/_authenticated/pesan/$peerId': typeof AuthenticatedPesanPeerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/masuk'
    | '/reset-password'
    | '/bantuanku'
    | '/beranda'
    | '/jelajahi'
    | '/notifikasi'
    | '/pesan'
    | '/profil'
    | '/riwayatku'
    | '/jelajahi/$category'
    | '/pesan/$peerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/masuk'
    | '/reset-password'
    | '/bantuanku'
    | '/beranda'
    | '/jelajahi'
    | '/notifikasi'
    | '/pesan'
    | '/profil'
    | '/riwayatku'
    | '/jelajahi/$category'
    | '/pesan/$peerId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/masuk'
    | '/reset-password'
    | '/_authenticated/bantuanku'
    | '/_authenticated/beranda'
    | '/_authenticated/jelajahi'
    | '/_authenticated/notifikasi'
    | '/_authenticated/pesan'
    | '/_authenticated/profil'
    | '/_authenticated/riwayatku'
    | '/_authenticated/jelajahi/$category'
    | '/_authenticated/pesan/$peerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  MasukRoute: typeof MasukRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masuk': {
      id: '/masuk'
      path: '/masuk'
      fullPath: '/masuk'
      preLoaderRoute: typeof MasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/riwayatku': {
      id: '/_authenticated/riwayatku'
      path: '/riwayatku'
      fullPath: '/riwayatku'
      preLoaderRoute: typeof AuthenticatedRiwayatkuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesan': {
      id: '/_authenticated/pesan'
      path: '/pesan'
      fullPath: '/pesan'
      preLoaderRoute: typeof AuthenticatedPesanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifikasi': {
      id: '/_authenticated/notifikasi'
      path: '/notifikasi'
      fullPath: '/notifikasi'
      preLoaderRoute: typeof AuthenticatedNotifikasiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jelajahi': {
      id: '/_authenticated/jelajahi'
      path: '/jelajahi'
      fullPath: '/jelajahi'
      preLoaderRoute: typeof AuthenticatedJelajahiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beranda': {
      id: '/_authenticated/beranda'
      path: '/beranda'
      fullPath: '/beranda'
      preLoaderRoute: typeof AuthenticatedBerandaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bantuanku': {
      id: '/_authenticated/bantuanku'
      path: '/bantuanku'
      fullPath: '/bantuanku'
      preLoaderRoute: typeof AuthenticatedBantuankuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesan/$peerId': {
      id: '/_authenticated/pesan/$peerId'
      path: '/$peerId'
      fullPath: '/pesan/$peerId'
      preLoaderRoute: typeof AuthenticatedPesanPeerIdRouteImport
      parentRoute: typeof AuthenticatedPesanRoute
    }
    '/_authenticated/jelajahi/$category': {
      id: '/_authenticated/jelajahi/$category'
      path: '/$category'
      fullPath: '/jelajahi/$category'
      preLoaderRoute: typeof AuthenticatedJelajahiCategoryRouteImport
      parentRoute: typeof AuthenticatedJelajahiRoute
    }
  }
}

interface AuthenticatedJelajahiRouteChildren {
  AuthenticatedJelajahiCategoryRoute: typeof AuthenticatedJelajahiCategoryRoute
}

const AuthenticatedJelajahiRouteChildren: AuthenticatedJelajahiRouteChildren = {
  AuthenticatedJelajahiCategoryRoute: AuthenticatedJelajahiCategoryRoute,
}

const AuthenticatedJelajahiRouteWithChildren =
  AuthenticatedJelajahiRoute._addFileChildren(
    AuthenticatedJelajahiRouteChildren,
  )

interface AuthenticatedPesanRouteChildren {
  AuthenticatedPesanPeerIdRoute: typeof AuthenticatedPesanPeerIdRoute
}

const AuthenticatedPesanRouteChildren: AuthenticatedPesanRouteChildren = {
  AuthenticatedPesanPeerIdRoute: AuthenticatedPesanPeerIdRoute,
}

const AuthenticatedPesanRouteWithChildren =
  AuthenticatedPesanRoute._addFileChildren(AuthenticatedPesanRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBantuankuRoute: typeof AuthenticatedBantuankuRoute
  AuthenticatedBerandaRoute: typeof AuthenticatedBerandaRoute
  AuthenticatedJelajahiRoute: typeof AuthenticatedJelajahiRouteWithChildren
  AuthenticatedNotifikasiRoute: typeof AuthenticatedNotifikasiRoute
  AuthenticatedPesanRoute: typeof AuthenticatedPesanRouteWithChildren
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRiwayatkuRoute: typeof AuthenticatedRiwayatkuRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBantuankuRoute: AuthenticatedBantuankuRoute,
  AuthenticatedBerandaRoute: AuthenticatedBerandaRoute,
  AuthenticatedJelajahiRoute: AuthenticatedJelajahiRouteWithChildren,
  AuthenticatedNotifikasiRoute: AuthenticatedNotifikasiRoute,
  AuthenticatedPesanRoute: AuthenticatedPesanRouteWithChildren,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRiwayatkuRoute: AuthenticatedRiwayatkuRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  MasukRoute: MasukRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
