// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const normalize = (value?: string) => value?.trim();
const isPlaceholderValue = (value?: string) => {
  if (!value) return true;
  const trimmed = value.trim();
  return [
    trimmed === "",
    trimmed.includes("your-"),
    trimmed.includes("paste"),
    trimmed.includes("replace"),
    trimmed.includes("example"),
    trimmed.includes("placeholder"),
    trimmed.includes("<"),
    trimmed.includes(">"),
  ].some(Boolean);
};

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = normalize(process.env.SUPABASE_URL);
    const SUPABASE_PUBLISHABLE_KEY = normalize(process.env.SUPABASE_PUBLISHABLE_KEY);

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || isPlaceholderValue(SUPABASE_URL) || isPlaceholderValue(SUPABASE_PUBLISHABLE_KEY)) {
      const message =
        "Supabase belum dikonfigurasi dengan benar. Isi URL project dan anon key di file .env sebelum membuka route yang butuh autentikasi.";
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
